### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by pumm1** [AventusM/MediHome#1]
_Koodi ladattu 1.12. klo 13:50_

Sivuston rakenne ja näkymä on selkeästi toteutettu käyttäjän kannalta. Rekisteröitymistä ei ole vielä toteutettuna, mutta kirjautuminen toimii dokumentaatiossa annetuilla tunnuksilla. Kirjaudu ulos-nappi näkyy myös, vaikkei käyttäjä ole kirjautuneena sisään, mikä korjautuisi helpolla if-lauseella HTML-tiedostossa, joka tarkistaa käyttäjän kirjautumisen. Hoitopyntöjen kotikäyntien kohdalla hyvin toteutettu ilmoitus käynnistä tai sen odottamisesta.

Kotikäynnin pyytäminen toimii, mutta sille voisi myös lisätä viestin, joka ilmoittaa onnistuneesta lisäämisestä. Joku sairaampi henkilö saattaa nähdä isomman listan näitä vanhoja pyyntöjä ja ei ehkä huomaa, onnistuiko prosessi. Kotikäyntipyynnön poistaminen toimii, mutta päivitys ei: **Undefined index: laakari_id**.

Hoito-ohjeiden lukeminen toimii, mutta lääkärin ID:n kohdalla (niin Hoito-ohjeen ja -pyynnön kohdalla) olisi ehkä mukavampi nähdä lääkärin nimi, jolloin asiakas kokee asioivansa ihmisen kanssa. Tämä ei kuitenkaan ole mikään iso juttu toiminnallisuuden kannalta.

**Comment by AventusM** [comment]
Kiitokset kommentista. Undefinex index - bugi on nyt korjattu. Otan ylös vinkit muista kappaleista.
